#!/usr/bin/env bash
# Description: <image> <namespace>
# Help: 
# Args: true

IMAGE="${1:-ubuntu:latest}"
NAME="$(basename ${IMAGE/%:*/})"
NAMESPACE="${2:-default}"

echo -n "apiVersion: batch/v1
kind: Job
metadata:
  name: $NAME
  namespace: $NAMESPACE
spec:
  template:
    spec:
      containers:
      - name: $NAME
        image: $IMAGE
        command: ["sleep", "3600"]
        resources:
          requests:
            memory: \"128Mi\"
            cpu: \"100m\"
          limits:
            memory: \"128Mi\"
            cpu: \"100m\"
"
