#!/usr/bin/env bash
# Description: <file> <track>
# Help: ffmpeg-help change-audio-track <FILE> <TRACK>
# Args: true

FILE="$1"
TRACK="$2"

ffmpeg -i "$FILE" -y \
    -map 0:v:0 -vcodec h264 \
    -map 0:a:"$TRACK" -acodec aac \
    "audio.$FILE"
