#!/usr/bin/env bash
# Description: <image> <namespace>
# Help: 
# Args: true

IMAGE="${1:-ubuntu:latest}"
NAME="$(basename ${IMAGE/%:*/})"
NAMESPACE="${2:-default}"

echo -n "apiVersion: v1
kind: Pod
metadata:
  name: $NAME
  namespace: $NAMESPACE
spec:
  containers:
  - name: $NAME
    image: $IMAGE
    ports:
      - containerPort: 3000
    resources:
      requests:
        memory: \"128Mi\"
        cpu: \"100m\"
      limits:
        memory: \"128Mi\"
        cpu: \"100m\"
"
