#!/usr/bin/env bash
# Description: <file> <language>
# Help: ffmpeg-help extract-subtitles <FILE> <LANGUAGE>
# Args: true

FILE="$1"
LANGUAGE="$2"

ffmpeg -i "$FILE" \
    -map "0:m:language:$LANGUAGE" \
    -map "-0:v" -map "-0:a" \
    "output.$LANGUAGE.srt"
