#!/usr/bin/env bash
# Description: <url>
# Help: 
# Args: true

URL="$1"

TITLE="$( \
    curl -L $URL 2>/dev/null \
    | pup 'h1 text{}' \
    | tr -d '\n' \
    | awk 'END {$1=$1; print}' \
)"
bookmarks interview add "[$TITLE]($URL)"
