#!/usr/bin/env bash
# Description: <file> <audio-track> <subtitles>
# Help: ffmpeg-help add-subtitles <FILE> <AUDIO-TRACK> <SUBTITLES>
# Args: true

FILE="$1"
AUDIO_TRACK="$2"
SUBTITLES="$3"

ffmpeg -i "$FILE" \
    -vf subtitles="$SUBTITLES" \
    -map "0:v:0" -vcodec h264 \
    -map "0:a:$AUDIO_TRACK" -acodec aac \
    "subs.$FILE"
